=== grumpylabs/freenginx/docs/dtd/changes.dtd
<!ENTITY  nbsp         "&#xA0;" >
<!ENTITY  mdash        "&#xA0;- " >


<!ELEMENT change_log   (section)* >

<!ELEMENT section      (changes)* >
<!ATTLIST section      title  CDATA #REQUIRED >

<!ELEMENT changes      (change)* >
<!ATTLIST changes      ver    CDATA #REQUIRED
                       date   CDATA #REQUIRED
>

<!ELEMENT change       (para)* >
<!ATTLIST change       type (bugfix | feature | change | security | workaround) #IMPLIED >

<!ELEMENT para         (#PCDATA | at | br | nobr)* >
<!ATTLIST para         lang (ru | en) #REQUIRED >

<!ELEMENT at           EMPTY >
<!ELEMENT br           EMPTY >
<!ELEMENT nobr         (#PCDATA) >

=== grumpylabs/freenginx/docs/xml/nginx/changes.xml
<?xml version="1.0" encoding="koi8-r" ?>
<!DOCTYPE change_log SYSTEM "../../dtd/changes.dtd" >


<change_log link="/nginx/changes.html" path="/nginx/" root=".."
            title="nginx">


<changes ver="0.1.1" date="11.10.2004">

<change type="feature">
<para lang="ru">
директива gzip_types.
</para>
<para lang="en">
the gzip_types directive.
</para>
</change>

<change type="feature">
<para lang="ru">
директива tcp_nodelay.
</para>
<para lang="en">
the tcp_nodelay directive.
</para>
</change>

<change type="feature">
<para lang="ru">
директива send_lowat работает не только на платформах, поддерживающих
kqueue NOTE_LOWAT, но и на всех, поддерживающих SO_SNDLOWAT.
</para>
<para lang="en">
the send_lowat directive is working not only on OSes that support
kqueue NOTE_LOWAT, but also on OSes that support SO_SNDLOWAT.
</para>
</change>

<change type="feature">
<para lang="ru">
эмуляция setproctitle() для Linux и Solaris.
</para>
<para lang="en">
the setproctitle() emulation for Linux and Solaris.
</para>
</change>

<change type="bugfix">
<para lang="ru">
ошибка при переписывании заголовка "Location" при проксировании.
</para>
<para lang="en">
the "Location" header rewrite bug fixed while the proxing.
</para>
</change>

<change type="bugfix">
<para lang="ru">
ошибка в модуле ngx_http_chunked_module, приводившая к зацикливанию.
</para>
<para lang="en">
the ngx_http_chunked_module module bug fixed that caused an endless loop.
</para>
</change>

<change type="bugfix">
<para lang="ru">
ошибки в модуле /dev/poll.
</para>
<para lang="en">
the /dev/poll module bugs fixed.
</para>
</change>

<change type="bugfix">
<para lang="ru">
при проксировании и использовании временных файлов ответы портились.
</para>
<para lang="en">
the responses were corrupted when the temporary files were used
while the proxing.
</para>
</change>

<change type="bugfix">
<para lang="ru">
бэкенду передавались запросы с неперекодированными символами.
</para>
<para lang="en">
the unescaped requests were passed to the backend.
</para>
</change>

<change type="bugfix">
<para lang="ru">
на Linux 2.4 при конфигурации сборки нужно было обязательно использовать
параметр --with-poll_module.
</para>
<para lang="en">
while the build configuration on Linux 2.4 the --with-poll_module parameter
was required.
</para>
</change>

</changes>


<changes ver="0.1.0" date="04.10.2004">

<change>
<para lang="ru">
Первая публично доступная версия.
</para>
<para lang="en">
The first public version.
</para>
</change>

</changes>


</change_log>
