=== grumpylabs/freenginx/docs/dtd/module.dtd
<!ELEMENT   module      (section+) >
<!ATTLIST   module
            name        CDATA #REQUIRED
            id          ID #REQUIRED
>

<!ELEMENT   section     (directive+ | para+) >
<!ATTLIST   section
            name        CDATA #REQUIRED
            id          ID #IMPLIED
>

<!ELEMENT   directive   (syntax+, default, context+, para+) >
<!ATTLIST   directive
            name        ID #REQUIRED
            appeared-in CDATA #IMPLIED
>

<!ELEMENT   syntax      (#PCDATA | argument | code | parameter | value)* >

<!ELEMENT   default     (#PCDATA | code)* >

<!ELEMENT   context     (#PCDATA)* >

<!ELEMENT   para        (#PCDATA | argument | c-def | c-func | code | command | emphasis | example | header | http-error | link | list | note | parameter | value | var)* >

<!ELEMENT   argument    (#PCDATA)* >

<!ELEMENT   c-def       (#PCDATA)* >

<!ELEMENT   c-func      (#PCDATA)* >

<!ELEMENT   code        (#PCDATA | value)* >

<!ELEMENT   command     (#PCDATA)* >

<!ELEMENT   emphasis    (#PCDATA)* >

<!ELEMENT   example     (#PCDATA)* >

<!ELEMENT   header      (#PCDATA)* >

<!ELEMENT   http-error  EMPTY >
<!ATTLIST   http-error
            code        CDATA #REQUIRED
            text        CDATA #IMPLIED
>

<!ELEMENT   link        (#PCDATA)* >
<!ATTLIST   link
            doc         CDATA #IMPLIED
            id          CDATA #IMPLIED
>

<!ELEMENT   list        (listitem+) >
<!ATTLIST   list
            type        (bullet | enum) #REQUIRED
>

<!ELEMENT   listitem    ANY >

<!ELEMENT   note        ANY >

<!ELEMENT   parameter   (#PCDATA)* >

<!ELEMENT   value       (#PCDATA)* >

<!ELEMENT   var         (#PCDATA)* >

<!ENTITY    nbsp        "&#xA0;" >
<!ENTITY    mdash       "&#xA0;- " >

=== grumpylabs/freenginx/docs/xml/http/ngx_http_mp4_module.xml
<?xml version="1.0"?>

<!DOCTYPE module SYSTEM "../../dtd/module.dtd">

<module name="HTTP MP4 Module" id="http_mp4_module">

<section name="Summary">

<para>
The module <code>ngx_http_mp4_module</code> provides pseudo-streaming
server-side support for H.264/AAC files typically having filename extensions
<pathname>.mp4</pathname>, <pathname>.m4v</pathname>,
and <pathname>.m4a</pathname>.
</para>

<para>
Pseudo-streaming works in alliance with conformant Flash players.
A player sends an HTTP request to the server with a start time
argument in the request URI’s query string (named simply
<parameter>start</parameter>
and specified in seconds), and the server responds with a stream
so that its start position corresponds to the requested time,
for example:
<example>
http://example.com/elephants_dream.mp4?start=238.88
</example>
This allows for a random seeking at any time, or starting playback
in the middle of a timeline.
</para>

<para>
To support seeking, H.264-based formats store the metadata
in the so-called “moov atom.”
It is a part of the file that holds the index information for the
whole file.
</para>

<para>
To start playback, a player first needs to read metadata.
This is done by sending a special request with the
<parameter>start=0</parameter>
argument.  Many encoding software will insert the metadata at
the end of the file.  This is bad for pseudo-streaming:
the metadata needs to be located at the beginning of the file,
or else the entire file will have to be downloaded before it
starts playing.  If a file is well-formed (with metadata at the
beginning of a file), nginx just sends back the contents of a file.
Otherwise, it has to read the file and prepare a new stream so that
metadata comes before media data.
This involves some CPU, memory, and disk I/O overhead,
so it is a good idea to
<link url="http://flowplayer.org/plugins/streaming/pseudostreaming.html#prepare">
prepare an original file for pseudo-streaming</link>,
rather than having nginx do this on every such request.
</para>

<para>
For a matching request with a non-zero
<parameter>start</parameter>
argument, nginx will read metadata from the file, prepare the
stream starting from the requested offset, and send it to a client.
This has the same overhead as described above.
</para>

<para>
If a matching request does not include the
<parameter>start</parameter>
argument, there is no overhead, and the file is just sent as a static resource.
Some players also support byte-range requests, and thus do not require
this module at all.
</para>

<para>
This module is not built by default, it should be enabled with the
<command>--with-http_mp4_module</command>
configuration parameter.
<note>
If you were using the third-party mp4 module, be sure to disable it.
</note>
</para>

<para>
A similar pseudo-streaming support for FLV files is provided by the module
<link doc="ngx_http_flv_module.xml">ngx_http_flv_module</link>.
</para>

</section>


<section id="example" name="Example Configuration">

<para>
<example>
location /video/ {
    mp4;
    mp4_buffer_size     1m;
    mp4_max_buffer_size 5m;
}
</example>
</para>

</section>


<section id="directives" name="Directives">

<directive name="mp4">
<syntax>mp4</syntax>
<default/>
<context>location</context>

<para>
Turns on module processing in a surrounding location.
</para>

</directive>


<directive name="mp4_buffer_size">
<syntax>mp4_buffer_size <argument>size</argument></syntax>
<default>mp4_buffer_size 512K</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
Sets the initial size of a memory buffer used to process MP4 files.
</para>

</directive>


<directive name="mp4_max_buffer_size">
<syntax>mp4_max_buffer_size <argument>size</argument></syntax>
<default>mp4_max_buffer_size 10M</default>
<context>http</context>
<context>server</context>
<context>location</context>

<para>
During metadata processing, a larger buffer may become necessary.
Its size cannot exceed the specified <argument>size</argument>,
or else nginx will return the server error
<http-status code="500" text="Internal Server Error"/>,
and log the following:
<example>
"/some/movie/file.mp4" mp4 moov atom is too large:
12583268, you may want to increase mp4_max_buffer_size
</example>
</para>

</directive>

</section>

</module>

=== grumpylabs/freenginx/docs/xml/http/ngx_http_core_module.xml
<!DOCTYPE module SYSTEM "../../dtd/module.dtd">

<module title="ngx_http_core_module"
        link="/en/docs/http/ngx_http_core_module.html"
        lang="en">

<section title="Directives">

<directive name="client_body_buffer_size">

<syntax>client_body_buffer_size <value>size</value></syntax>
<default>client_body_buffer_size 8k/16k</default>
<context>http, server, location</context>

<para>
Directive sets client request body buffer size.
If the request body is larger than the buffer,
then the whole body or some its part is written to temporary file.
By default buffer size is equal to 2 memory page sizes.
This is 8K on x86, other 32-bit platforms, and x86-64.
It is usually 16K on other 64-bit platforms.
</para>

</directive>


<directive name="sendfile">

<syntax>sendfile <value>[on|off]</value></syntax>
<default>sendfile off</default>
<context>http, server, location</context>

<para>
Directive enables or disables sendfile() usage.
</para>

</directive>

</section>

</module>

=== grumpylabs/freenginx/docs/xml/ngx_core_module.xml
<?xml version="1.0"?>

<!DOCTYPE module SYSTEM "../dtd/module.dtd">

<module name="Core Module" id="core_module">

<section id="example" name="Example Configuration">

<para>
<example>
user www www;
worker_processes 2;

error_log /var/log/nginx-error.log info;

events {
    use kqueue;
    worker_connections 2048;
}

...
</example>
</para>

</section>


<section id="directives" name="Directives">

<directive name="daemon">
<syntax>daemon <value>on</value> | <value>off</value></syntax>
<default>daemon on</default>
<context>main</context>

<para>
Determines whether nginx should become a daemon.
Mainly used during development.
</para>

</directive>


<directive name="env">
<syntax>env <argument>VAR</argument>[=<argument>VALUE</argument>]</syntax>
<default>env TZ</default>
<context>main</context>

<para>
Allows to limit a set of environment variables, change their values,
or create new environment variables, for the following cases:
<list type="bullet">

<listitem>
variable inheritance during a
<link doc="control.xml" id="upgrade">live upgrade</link>
of an executable file;
</listitem>

<listitem>
use of variables by the module
<link doc="http/ngx_http_perl_module.xml">ngx_http_perl_module</link>;
</listitem>

<listitem>
use of variables by worker processes.
Please bear in mind that controlling system libraries in this way
is not always possible as it is not uncommon for libraries to check
variables only during initialization, well before they can be set
using this directive.
An exception from this is an above mentioned
<link doc="control.xml" id="upgrade">live upgrade</link>
of an executable file.
</listitem>

</list>
</para>

<para>
The TZ variable is always inherited and made available to the module
<link doc="http/ngx_http_perl_module.xml">ngx_http_perl_module</link>,
unless configured explicitly.
</para>

<para>
Usage example:
<example>
env MALLOC_OPTIONS;
env PERL5LIB=/data/site/modules;
env OPENSSL_ALLOW_PROXY_CERTS=1;
</example>
</para>

</directive>

<directive name="include">
<syntax>include <argument>file</argument> | <argument>mask</argument></syntax>
<default/>
<context/>

<para>
Includes another <argument>file</argument>, or files matching the
specified <argument>mask</argument>, into configuration.
Included files should consist of
syntactically correct directives and blocks.
</para>

<para>
Usage example:
<example>
include mime.types;
include vhosts/*.conf;
</example>
</para>

</directive>


<directive name="master_process">
<syntax>master_process <value>on</value> | <value>off</value></syntax>
<default>master_process on</default>
<context>main</context>

<para>
Determines whether worker processes are started.
This directive is intended for nginx developers.
</para>

</directive>


<directive name="pid">
<syntax>pid <argument>file</argument></syntax>
<default>pid nginx.pid</default>
<context>main</context>

<para>
Defines a <argument>file</argument> which will store the process ID of the main process.
</para>

</directive>


<directive name="ssl_engine">
<syntax>ssl_engine <argument>device</argument></syntax>
<default/>
<context>main</context>

<para>
Defines the name of the hardware SSL accelerator.
</para>

</directive>


<directive name="user">
<syntax>user <argument>user</argument> [<argument>group</argument>]</syntax>
<default>user nobody nobody</default>
<context>main</context>

<para>
Defines <argument>user</argument> and <argument>group</argument>
credentials used by worker processes.
If <argument>group</argument> is omitted, a group whose name equals
that of <argument>user</argument> is used.
</para>

</directive>


<directive name="timer_resolution">
<syntax>timer_resolution <argument>interval</argument></syntax>
<default/>
<context>main</context>

<para>
Reduces timer resolution in worker processes, thus reducing the
number of <c-func>gettimeofday</c-func> system calls made.
By default, <c-func>gettimeofday</c-func> is called each time
on receiving a kernel event.
With reduced resolution, <c-func>gettimeofday</c-func> is only
called once per specified <argument>interval</argument>.
</para>

<para>
Example:
<example>
timer_resolution 100ms;
</example>
</para>

<para>
An internal implementation of interval depends on the method used:
<list type="bullet">

<listitem>
an <c-def>EVFILT_TIMER</c-def> filter if <value>kqueue</value> is used;
</listitem>

<listitem>
<c-func>timer_create</c-func> if <value>eventport</value> is used;
</listitem>

<listitem>
<c-func>setitimer</c-func> otherwise.
</listitem>

</list>
</para>

</directive>


<directive name="worker_rlimit_core">
<syntax>worker_rlimit_core <argument>size</argument></syntax>
<default/>
<context>main</context>

<para>
Changes the limit on the largest size of a core file
(<c-def>RLIMIT_CORE</c-def>) for worker processes.
Used to increase the limit without restarting the main process.
</para>

</directive>


<directive name="worker_rlimit_nofile">
<syntax>worker_rlimit_nofile <argument>number</argument></syntax>
<default/>
<context>main</context>

<para>
Changes the limit on the maximum number of open files
(<c-def>RLIMIT_NOFILE</c-def>) for worker processes.
Used to increase the limit without restarting the main process.
</para>

</directive>


<directive name="worker_priority">
<syntax>worker_priority <argument>number</argument></syntax>
<default>worker_priority 0</default>
<context>main</context>

<para>
Defines a scheduling priority for worker processes like is
done by the <command>nice</command>: a negative
<argument>number</argument>
means higher priority.
Allowed range normally varies from -20 to 20.
</para>

<para>
Example:
<example>
worker_priority -10;
</example>
</para>

</directive>


<directive name="worker_processes">
<syntax>worker_processes <argument>number</argument></syntax>
<default>worker_processes 1</default>
<context>main</context>

<para>
Defines the number of worker processes.
</para>

</directive>


<directive name="working_directory">
<syntax>working_directory <argument>directory</argument></syntax>
<default/>
<context>main</context>

<para>
Defines a current working directory for a worker process.
It is primarily used when writing a core-file, in which case
a working process should have write permission for the
specified directory.
</para>

</directive>

</section>

</module>
